In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([9, 8, 7], name = 'a')
b = tf.constant([1, 2, 3], name = 'b')

In [16]:
soma = a + b

tf.Tensor([9 8 7], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [4]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [5]:
print(a)

tf.Tensor([9 8 7], shape=(3,), dtype=int32)


In [6]:
print(soma)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [17]:
a1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'a1')

In [8]:
type(a1)

tensorflow.python.framework.ops.EagerTensor

In [9]:
print(a1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
a1.shape

TensorShape([2, 3])

In [11]:
b1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'b1')

In [12]:
soma1 = tf.add(a1, b1)

In [13]:
print(a1)
print('\n')
print(b1)
print('\n')
print(soma1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [14]:
a2 = tf.constant([[1,2,3], [4,5,6]])
b2 = tf.constant([[1], [2]])
soma2 = tf.add(a2, b2)

In [15]:
print(a2)
print('\n')
print(b2)
print('\n')
print(soma2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)


tf.Tensor(
[[2 3 4]
 [6 7 8]], shape=(2, 3), dtype=int32)
